### ISSUE TITLE
artifacts indiening pagina

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#136]
de functionaliteit voor het downloaden van docker artifacts moet nog gebeuren

**Comment by Bendemeurichy** [comment]
klaar maar moet nog getest worden

**Comment by sPAICEcake** [comment]
Er moet een project aangemaakt worden, waarbij er tijdens de restrictietesten output gegenereerd wordt (eventueel gwn print ofzo), dan kan dit effectief deftig getest worden

**Comment by LGDTimtou** [comment]
Ik heb dit getest en dit werkt dus concreet na de verandering in pr: https://github.com/SELab-2/UGent-4/pull/237
Deze zou nog gereviewed moeten worden en dan zet ik deze op de server en kan deze issue geclosed worden
