### ISSUE TITLE
laat studenten groepen kiezen

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#137]
switch in groepen pagina is nog niet functioneel.
Nood aan extra popup voor studenten om groepen te kiezen

**Comment by sPAICEcake** [comment]
Is dit geen dubbele issue?

**Comment by Bendemeurichy** [comment]
ah ja goed gezien, ik denk omdat dit al in de backend zit en nog in de frontend in orde moet komen
