### ISSUE TITLE
parameters toevoegen add/change subjectspage

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#148]
Er zijn nog 2 missende parameters in de fileuploadknop die gebruikt wordt in de AddChangeSubjectPage om het handlen van de geuploade bestanden te regelen.
Dit zorgt ervoor dat de applicatie niet door de build stap geraakt.

**Comment by Bendemeurichy** [comment]
@ManedW0lf er zijn nu nieuwe errors omdat je het resultaat van papa.parse assigned aan een var maar papa.parse returned void

**Comment by sPAICEcake** [comment]
Is dit tijdens de cleanup gebeurd? Maw kan deze issue gesloten worden?
