### ISSUE TITLE
Frontend testen afwerken

### ISSUE THREAD

**Issue by sPAICEcake** [SELab-2/UGent-4#167]

**Comment by mathis2003** [comment]
Hier is de checklist van de testen die nog moeten gebeuren:

- [ ] assignmentPage
- [ ] groupsPage
- [ ] loginPage
- [ ] scoresPage
- [ ] subjectsPage
- [ ] submissionsPage

Als je aan een van de puntjes gaat beginnen, zeg dat dan in deze issue op voorhand zodat niemand anders er al ondertussen mee begint. Als het af is, zet er dan een vinkje.

**Comment by mathis2003** [comment]
Ik ga eens kijken om testen de schrijven voor de subjectsPage.

**Comment by ArnoutAllaert** [comment]
Ik heb de component testen geupdatet: nieuwe aangemaakt, verouderde verwijderd en eentje verplaatst naar de scoresPage.
Enkel de DeadlineCalender test krijg ik voorlopig niet gefixt.

**Comment by ArnoutAllaert** [comment]
Ik heb gezorgd dat alle component testen de UI elementen opzoeken via een id, in plaats van de naam van het element. Dit is handiger aangezien er soms meerdere van hetzelfde element zijn en het dan lastig kan zijn om diegene te selecteren die je eigenlijk wilt. Vooral voor de e2e testen zal dit veel gemakkelijker zijn. 
Ik zal nu kijken om de page testen ook aan te passen en eventueel nog wat page testen toe te voegen, maar ik denk dat het voor de meeste pages beter is om al e2e testen ervoor te maken.

**Comment by mathis2003** [comment]
Ok, dat is goed, ik ben momenteel wat tutorials aan het kijken over e2e testen omdat ik e nog nooit mee gewerkt heb. Maar vanavond nog zal ik al proberen om wat e2e testen te schrijven.

**Comment by ArnoutAllaert** [comment]
Het is eigenlijk heel gelijkaardig aan de component testen, maar in plaats van 1 component te mounten, ga je op de site gaan werken.

**Comment by mathis2003** [comment]
Ik heb trouwens net iets interessants gezien dat wel handig kan zijn voor ons. Je kan aan de jsx elementen een data-cy tag toevoegen. Dan kan je zeer gemakkelijk daarop zoeken in de tests.

**Comment by ArnoutAllaert** [comment]
Dat is gelijkaardig als met id's werken vind ik.  [Cypress zelf zegt wel dat het beter is om met cy-data te werken](https://docs.cypress.io/guides/references/best-practices), maar ik zie niet echt het verschil tussen cy-data of id, het moet sowieso op een pagina uniek zijn, want anders krijgt je terug meerdere objecten met cy.get
![image](https://github.com/SELab-2/UGent-4/assets/43027876/2468050d-7dcd-465d-9372-d1c4cd596927)

**Comment by sPAICEcake** [comment]
> Hier is de checklist van de testen die nog moeten gebeuren:
> 
> * [ ]  assignmentPage
> * [ ]  groupsPage
> * [ ]  loginPage
> * [ ]  scoresPage
> * [ ]  subjectsPage
> * [ ]  submissionsPage
> 
> Als je aan een van de puntjes gaat beginnen, zeg dat dan in deze issue op voorhand zodat niemand anders er al ondertussen mee begint. Als het af is, zet er dan een vinkje.

Deze page testen zijn al in orde werd er daarnet op de vergadering gezegd, dus mss aanvullen :)

**Comment by sPAICEcake** [comment]
#301
