### ISSUE TITLE
archiveren vakken

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#169]
als alle projecten in een vak zijn gearchiveerd is een vak gearchiveerd

**Comment by gusvanpoucke** [comment]
Kzal hier naar kijken

**Comment by gusvanpoucke** [comment]
https://github.com/SELab-2/UGent-4/pull/198 functionaliteit werkt in deze PR

**Comment by Bendemeurichy** [comment]
top, bedankt
