### ISSUE TITLE
student homepage ziet ook onzichtbare projecten

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#173]
De student homepage ziet voorlopig nog onzichtbare projecten omdat dit niet wordt gecheckt.
Zou opgelost moeten zijn met 1 check in Mainpage.tsx

**Comment by gusvanpoucke** [comment]
Dit lijkt al opgelost te zijn.
Momenteel zijn onzichtbare projecten op de mainPage ook onzichtbaar voor leerkrachten, willen wij dit zo houden?

**Comment by Bendemeurichy** [comment]
voor leerkrachten beter niet lijkt me, dat heeft niet zo veel nut

**Comment by gusvanpoucke** [comment]
Kzal dit fixen dan

**Comment by sPAICEcake** [comment]
mag ik dit sluiten door deze PR te mergen? #196

**Comment by gusvanpoucke** [comment]
yep daarmee is het opgelost
