### ISSUE TITLE
lesgevers opvragen

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#181]
Leerlingen kunnen hun lesgevers niet opvragen omdat ze hier geen toegang tot hebben.

**Comment by LGDTimtou** [comment]
Zal dit ook eens bekijken bedankt.

**Comment by LGDTimtou** [comment]
Wat bedoel je hier eigenlijk mee, want een leerling kan toch gewoon zijn eigen vakken zien?
In die vakken zit dan toch gewoon een veld met lesgevers of niet?

**Comment by Bendemeurichy** [comment]
Ja, maar dat is enkel het id.
Leerlingen hebben geen toegang om de naam van de leerkracht op te vragen

**Comment by LGDTimtou** [comment]
Juist.
Zal dit bekijken

**Comment by LGDTimtou** [comment]
Is opgelost in deze commit: https://github.com/SELab-2/UGent-4/pull/182/commits/446cd888c5921e0d58ac19a1158ce77dfe490512

Zit in deze pull request: https://github.com/SELab-2/UGent-4/pull/182
