### ISSUE TITLE
Visual improvement

### ISSUE THREAD

**Issue by sPAICEcake** [SELab-2/UGent-4#184]
De layout verbeteren en bepaalde pagina's mooier en duidelijker maken (mbv schaduw en outline, ...)

**Comment by Bendemeurichy** [comment]
![image](https://github.com/SELab-2/UGent-4/assets/48103261/114f74e7-fe96-42ba-a805-a5ab6da3138c)
@friedrecursion 
De allignment hier is een beetje vreemd

**Comment by sPAICEcake** [comment]
Ik heb gezien dat andere groepen een soort 'wereldbol' symbooltje gebruiken om de taal te veranderen. Dit is mss iets waar wij ook kunnen voor kijken, want dat is wel veel duidelijker dan dat je op je profielfoto moet klikken

**Comment by gusvanpoucke** [comment]
![image](https://github.com/SELab-2/UGent-4/assets/159711661/52384333-21ed-4183-96c9-2e3c7f324732)
voelt een beetje raar dat de save knop bovenaan staat hier

**Comment by sPAICEcake** [comment]
Wat kleinde dingen die ik ook nog heb opgemerkt daarnet:

GroupsPage:
	Groups toggle op GroupsPage staat altijd op uit bij het herladen van de pagina
	Globale groep_id wordt getoond ipv groepsnummer per vak
	Er mankeert een terugknop in de header

AssigmentPage:	
	Globale submission_id wordt getoond ipv persoonlijk nummer van indiening per student/groep

**Comment by Bendemeurichy** [comment]
geen terugknop op de groupspage is bewust omdat je een cancel knop hebt langswaar je dan terug zou gaan, dat heb ik ook gedaan bij de add/change assignmentpage

**Comment by sPAICEcake** [comment]
> geen terugknop op de groupspage is bewust omdat je een cancel knop hebt langswaar je dan terug zou gaan, dat heb ik ook gedaan bij de add/change assignmentpage

Ahja oké, wel logisch. Mss is het dan wel duidelijker om Annuleren/Cancel op die knop te zetten ipv een kruisje

**Comment by Bendemeurichy** [comment]
Het lettertype op deze header is nogal groot in vergelijking met de data
![image](https://github.com/SELab-2/UGent-4/assets/48103261/5280501b-3848-4277-acc2-a8d31b56be86)

**Comment by Bendemeurichy** [comment]
vaknaam wordt niet ingevuld in tekstvak maar staat wel in de header, mij lijkt het dat dit zou moeten overeenkomen zodat de lesgever ook de bestaande naam kan aanpassen ipv opnieuw typen
![image](https://github.com/SELab-2/UGent-4/assets/48103261/610e1e4c-ece4-4005-be2d-313f231d31c5)

**Comment by sPAICEcake** [comment]
SubmissionPage:
	status is 'not yet completed' en Result blijft maar laden

**Comment by sPAICEcake** [comment]
Zou het geen idee zijn om per vak ook gwn een lijst met de ingeschreven studenten te kunnen opvragen vanuit de subjectPage (eventueel kleine pop-up die de namen toont)?

**Comment by Bendemeurichy** [comment]
> SubmissionPage: status is 'not yet completed' en Result blijft maar laden

das doordat de docker nog niet op de server was opgezet dus de testen werden nog niet gerunned

**Comment by gusvanpoucke** [comment]
![image](https://github.com/SELab-2/UGent-4/assets/159711661/2557c288-9fc5-43ab-b2c1-ff625a32bbc8)
deze knop start altijd op uit als je de pagina opent, ook als groepen aan staat voor dit project (maw max_groep_grootte staat op een waarde groter dan 1)

**Comment by Bendemeurichy** [comment]
Ik snap niet meteen waarom users hier klikbaar zijn
[Screencast from 2024-04-29 15-12-45.webm](https://github.com/SELab-2/UGent-4/assets/48103261/24bac4f0-9380-415d-a25c-21a7e2024bd6)

**Comment by Bendemeurichy** [comment]
Er staat studentnummer bij lesgevers uploadknop
![image](https://github.com/SELab-2/UGent-4/assets/48103261/a3ad8330-1e00-4ceb-9d9a-ada3825da6c2)

**Comment by gusvanpoucke** [comment]
Op alle paginas waar de score word weergegeven, als een groep nog geen score gekregen heeft word er nu de score 0/20 getoont maar dit kan verwarrend zijn. Beter als er gewoon "geen score" getoont word

**Comment by gusvanpoucke** [comment]
Misschien ook handig om ergens in de header te tonen op welk account de gebruiker ingelogd is

**Comment by sPAICEcake** [comment]
Bij de courseCard is het mss visueel mooier om het 'pin' symbool om te wisselen met het weergeven van het aantal studenten

**Comment by friedrecursion** [comment]
groep pagina:
studenten matrix + student kunnen opzoeken

indieningen pagina:

geslaagd, gefaald kleur geven

**Comment by friedrecursion** [comment]
algemeen:  als een lijst leeg is: tekstje : geen {vb submissions}

**Comment by sPAICEcake** [comment]
Calendar op Mainpage een beetje visueel verfijnen

**Comment by Bendemeurichy** [comment]
Ik vind het een beetje vreemd om van alle knoppen "main actions" te maken door alles de primaire kleur te geven, @friedrecursion

**Comment by friedrecursion** [comment]
Ik vind da er wel clean uitzien da alles hetzelfde is. wil je alles secundairy kleur of sommige primair en dan andere secundairy? @Bendemeurichy

**Comment by Bendemeurichy** [comment]
@friedrecursion 
Ik zou uw main actie(s) in de primaire kleur doen en dan al de rest in de secundaire kleur, dan weet de gebruiker op wat hij moet focussen.
Is gewoon best practice [button style guide](https://balsamiq.com/learn/articles/button-design-best-practices/)

**Comment by friedrecursion** [comment]
![test_script_ui_before](https://github.com/SELab-2/UGent-4/assets/111664155/ad77e8e5-b83f-432c-a5b7-d46272418383)
![test_script_ui_after](https://github.com/SELab-2/UGent-4/assets/111664155/e2e5eff0-3fe1-4695-a9f5-f14f4d6938dc)
@mathis2003 u test script ziet er nu zo uit.

**Comment by Bendemeurichy** [comment]
wa is het verschil tussen save template en save?

**Comment by Bendemeurichy** [comment]
![image](https://github.com/SELab-2/UGent-4/assets/48103261/9341e2d6-b372-45c5-a354-90c8acabfb8b)
deze dialog ziet er een beetje rommelig uit

**Comment by mathis2003** [comment]
@friedrecursion De buttons zien er goed uit, maar zou het toch niet beter zijn om ze in de app-bar te houden? Op die manier heb je meer plaats voor de effectieve text editor

**Comment by mathis2003** [comment]
> wa is het verschil tussen save template en save?

@Bendemeurichy save template betekent dat je de file saved als een template, om dan later te gebruiken voor bijvoorbeeld andere projecten. Save dient om de code als restrictie bij het huidige project te zetten.

**Comment by friedrecursion** [comment]
@mathis2003 als da nie noodzakelijk is liever nie, zoda alle paginas meer dezelfde layout hebben

**Comment by friedrecursion** [comment]
![voeg_restrictie_toe_after](https://github.com/SELab-2/UGent-4/assets/111664155/e20472e9-2c8c-43a5-bdd8-abf607f3690b)
@Bendemeurichy ziet er nu zo uit.

**Comment by mathis2003** [comment]
Hmmm, hieruit zou ik afleiden dat de "Moet slagen" bij de templates hoort, en de "Open met UI" bij upload en nieuw script.
Als je kan zou ik de volgende dingen doen:
1. de template buttons al sowieso renderen in een soort van scrollable lijst (als er tijd over is, met een zoekbar misschien maar dat is wel heel veel werk voor zo een kleine feature waarschijnlijk.
2. "Open met UI" zou ik in een soort van header of footer van de scrollable lijst steken, zodat het duidelijk hoort bij de templates.
3. "Moet slagen" zou ik misschien links onder zetten, links van "Annuleer" dan ofzo.

**Comment by friedrecursion** [comment]
![popupv2](https://github.com/SELab-2/UGent-4/assets/111664155/abc56816-a7cd-4c8c-ba08-500b9e6ea2e9)

@mathis2003 ik vindt dit duidelijk genoeg. (die must pass kan ik niet zomaar bij cancel zetten omdat da in een andere file is en functies in deze file die gebruiken)

**Comment by mathis2003** [comment]
@friedrecursion kan je misschien juist nog de template buttons in een scrollable lijst zetten dan? Want als er meer templates komen dan zal de box waarschijnlijk niet groot genoeg zijn.

**Comment by mathis2003** [comment]
Misschien kunnen we op termijn zelfs die "must pass" weglaten uit de popup en gewoon in de rij elementen van de restricties steken. Dat zal waarschijnlijk properder en duidelijker zijn.

**Comment by friedrecursion** [comment]
@mathis2003 kzal da scrollable maken en btw kheb die save knop enz terug in de header gestoken zodat wa overeenkomt met u pagina voor 'open met ui'. die "must pass" gaak nu effekes laten omdat da functionaliteit is, da kank nie zomaar doen

**Comment by friedrecursion** [comment]
![wide](https://github.com/SELab-2/UGent-4/assets/111664155/d194304e-9814-4d2e-8a37-9eab1be0eaeb)
![notwide](https://github.com/SELab-2/UGent-4/assets/111664155/75b7ed0c-8e28-47e5-9375-d8233557eb86)

wat is jullie voorkeur

**Comment by LGDTimtou** [comment]
Ik zou iets ertussen nemen maar toch wat meer neigend naar de randen

**Comment by mathis2003** [comment]
Ik denk hetzelfde als Timon hier.

**Comment by friedrecursion** [comment]
Kheb idd iets ertussen genomen

**Comment by friedrecursion** [comment]
![lookup_001](https://github.com/SELab-2/UGent-4/assets/111664155/3b5ae465-be5d-4344-abda-ec1ed4f0e756)
Kben bezig met studenten lookup. ma da component werkt nie deftig + ik vind een beetje cluttered met En een lijst En een grid daarachter. imo is gwn een grid wel cleaner.

**Comment by mathis2003** [comment]
De component werkt wel deftig, het matcht de "ro" van Arthur Werb"ro"uck. Ik weet niet of je kan aanpassen dat het enkel matcht met de eerste letters, maar ik zou het zeker houden wat we nu hebben. Ik snap dat de lijst voor de grid misschien wat ambetant eruit ziet. Maar het is wel veel beter dan gaan zoeken in een grid van 150-300 studenten. En soms zelfs meer.

**Comment by mathis2003** [comment]
Je kan misschien eens proberen om de dropdown een sterke outline te geven zodat het niet echt meer opgaat in de achtergrond-grid.

**Comment by friedrecursion** [comment]
Cv, kzal da proberen. Enkel nog probleem is dat een groupage inladen met veel studenten echt nog onaanvaardbaar traag is. Voor die 9 ist al 10 seconden ofz.

**Comment by mathis2003** [comment]
Hmmm dat is waarschijnlijk omdat er voor elke student een fetch wordt gedaan om data op te vragen van die student. misschien kunnen we in de backend wat extra informatie bij de lijst van studenten buiten enkel hun id zetten ofzo. Dat is een klein beetje meer redundantie dan maar wel de optimalisatie waard. Wt denk jij hiervan @LGDTimtou ?

**Comment by Bendemeurichy** [comment]
> Hmmm dat is waarschijnlijk omdat er voor elke student een fetch wordt gedaan om data op te vragen van die student. misschien kunnen we in de backend wat extra informatie bij de lijst van studenten buiten enkel hun id zetten ofzo. Dat is een klein beetje meer redundantie dan maar wel de optimalisatie waard. Wat denk jij hiervan @LGDTimtou ?

Ik kan zoals robbe in de frontend alle studenten opvragen en dan filteren maar dit is natuurlijk totaal niet schaalbaar.
Het gemakkelijkste zou idd een sql join met de studenten tabel voor de naam ofzo in de response.

**Comment by gusvanpoucke** [comment]
![image](https://github.com/SELab-2/UGent-4/assets/159711661/b4ecd198-4966-4647-a4ca-8e264e469d8b)
de description van een project staat 2 keer op de assignmentPage, onder de titel en in da vakje.
Die eerste onder de titel mag weg

**Comment by Bendemeurichy** [comment]
> ![image](https://private-user-images.githubusercontent.com/159711661/331878023-b4ecd198-4966-4647-a4ca-8e264e469d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzA5OTQsIm5iZiI6MTcxNjEzMDY5NCwicGF0aCI6Ii8xNTk3MTE2NjEvMzMxODc4MDIzLWI0ZWNkMTk4LTQ5NjYtNDY0Ny1hNGNhLThlMjY0ZTQ2OWQ4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOVQxNDU4MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODI5ZTBjYmYyZDAxMzU1ODQ1ODRlYTdhOWI4ODI4NTg0MzY2MTkzMjVjM2U1YWYyMGUyYjA3M2Q0ZDRkMGJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Osu2MjCl-PeyyyyhydswaR-QkBrdwp2DOH8Mb8eEGtQ) de description van een project staat 2 keer op de assignmentPage, onder de titel en in da vakje. Die eerste onder de titel mag weg

zal dit snel doen

**Comment by sPAICEcake** [comment]
afgehandeld in #285
