### ISSUE TITLE
Bug testing en fixing

### ISSUE THREAD

**Issue by sPAICEcake** [SELab-2/UGent-4#185]
+ opmerkingen over visuals doorgeven aan Elias

**Comment by sPAICEcake** [comment]
CoursePage:
	Er staat 'No submissions', maar er is weldegelijk een submission ingediend

**Comment by gusvanpoucke** [comment]
https://github.com/SELab-2/UGent-4/pull/197 zou hier gefixt moeten zijn

**Comment by Bendemeurichy** [comment]
#199

**Comment by sPAICEcake** [comment]
#201

**Comment by sPAICEcake** [comment]
'+'-knop op mainpage bij teacher geeft 404 ('https://sel2-4.ugent.be/api/vakken/edit/')

**Comment by Bendemeurichy** [comment]
> kleine bug maar na het toevoegen van een leerkracht/student wordt het veld niet gecleared. Het lijk mij beter dat dit wel gebeurt/ ![image](https://private-user-images.githubusercontent.com/48103261/327729563-0beec5dc-c09e-489c-9c90-f1fcccfdb9e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MzI4ODgsIm5iZiI6MTcxNDczMjU4OCwicGF0aCI6Ii80ODEwMzI2MS8zMjc3Mjk1NjMtMGJlZWM1ZGMtYzA5ZS00ODljLTljOTAtZjFmY2NjZmRiOWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDEwMzYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwZDc5ZTg3YTIxZDU3M2VmOGJiNmNiZjQyMmM3MTAyMDgyYzMyM2E5ZWUzOTIwYWM2OWE4MjZjOTYzMTBjMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-scpn83r3XfxLb_bESlZL5-44-fjhlfmwZoZ6Tiojx0)


opgelost in #217

**Comment by gusvanpoucke** [comment]
https://github.com/SELab-2/UGent-4/issues/220

**Comment by gusvanpoucke** [comment]
Momenteel als de backend een error opgooit doet de frontend hier niks mee wat verwarrend kan zijn.
bv. als een project word aangemaakt zonder opgavebestand dan verschijnt dat project gwn niet

**Comment by Bendemeurichy** [comment]
ik dacht dat een bestand optioneel was dus dit zit zo in de frontend

> Momenteel als de backend een error opgooit doet de frontend hier niks mee wat verwarrend kan zijn. bv. als een project word aangemaakt zonder opgavebestand dan verschijnt dat project gwn niet

**Comment by Bendemeurichy** [comment]
> Momenteel als de backend een error opgooit doet de frontend hier niks mee wat verwarrend kan zijn. bv. als een project word aangemaakt zonder opgavebestand dan verschijnt dat project gwn niet

@LGDTimtou vind jij het logischer om in de backend opgave bestanden optioneel te maken of verplicht te maken in de frontend?

**Comment by gusvanpoucke** [comment]
> @gusvanpoucke de kalender toont nu alle deadlines ook van vakken dat je niet hebt. ![image](https://private-user-images.githubusercontent.com/48103261/328012451-1ed6cb9d-7c92-458e-8d36-bcaf7526df4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTg3NTQsIm5iZiI6MTcxNDkxODQ1NCwicGF0aCI6Ii80ODEwMzI2MS8zMjgwMTI0NTEtMWVkNmNiOWQtN2M5Mi00NThlLThkMzYtYmNhZjc1MjZkZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE0MTQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3MWI2ZmIwNWUxNWQ4MGE0NzhmMDI5MzNhZmYyNzVhNDZlOGZjOWY1NDY2N2NiODU5NTcxNDViYzY4ZDEyOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5v9O_jfCW2b6sO4qwy0vNdYqUI5EOZySoLtit7Bdwr8)

https://github.com/SELab-2/UGent-4/pull/224 hier gefixt

**Comment by gusvanpoucke** [comment]
Op de groep pagina als je het maximum aantal mensen in een groep aanpast herlaad de pagina meteen, wat de waarde terug reset naar wat hij daarvoor was. De save knop lijkt hier ook niet te werken

**Comment by Bendemeurichy** [comment]
normaal herlaad de groepen pagina inderdaad als de grootte wordt aangepast, dan wordt iedereen naar links verplaatst om herverdeeld te worden. Dan zal er een fout in geslopen zijn bij het laden misschien

**Comment by gusvanpoucke** [comment]
Er is ook een probleem met hoe de AddChangeAssignment pagina het tijdstip invult wat ervoor zorgt dat elke keer dat je een project aanpast het tijdstip 2 uur vervroegt ook als je niks aanpast.

**Comment by gusvanpoucke** [comment]
> Calendar: Deadlines doen raar met tijdzone omzetting van uren dicht bij datumwisseling



> Er is ook een probleem met hoe de AddChangeAssignment pagina het tijdstip invult wat ervoor zorgt dat elke keer dat je een project aanpast het tijdstip 2 uur vervroegt ook als je niks aanpast.


bleken allebei heel makkelijke fixes te zijn
https://github.com/SELab-2/UGent-4/pull/232 zijn hier opgelost

**Comment by gusvanpoucke** [comment]
https://github.com/SELab-2/UGent-4/issues/267

**Comment by sPAICEcake** [comment]
Deze issue is behandeld, alle problemen die ontstaan zijn door de laatste merge worden elders behandeld
