### ISSUE TITLE
indieningen updaten niet indien nieuwe indiening wordt toegevoegd

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#186]
[Screencast from 2024-04-24 11-09-46.webm](https://github.com/SELab-2/UGent-4/assets/48103261/ac936e6a-15f2-41b8-9bff-633c2c47bd29)

**Comment by Bendemeurichy** [comment]
@friedrecursion @gusvanpoucke Zou een van jullie hier eens naar willen kijken?
normaal is dat gewoon een dependancie van de useeffect waar de data wordt ingeladen toevoegen.

**Comment by gusvanpoucke** [comment]
Ik ga er eens naar kijken

**Comment by gusvanpoucke** [comment]
opgelost in deze PR https://github.com/SELab-2/UGent-4/pull/192
