### ISSUE TITLE
Vakken/Indieningen verschijnen onafhankelijjk van of de student ervoor ingeschreven is/de indiening gedaan heeft

### ISSUE THREAD

**Issue by gusvanpoucke** [SELab-2/UGent-4#189]
- op mainpage
- op assignmentpage
- ...

**Comment by Bendemeurichy** [comment]
[pr](https://github.com/SELab-2/UGent-4/pull/182#issuecomment-2071777331) dit is aangepast aan de backend maar nog niet in de frontend, zal dit in orde brengen

**Comment by sPAICEcake** [comment]
#213 wordt opgelost in deze pull request
