### ISSUE TITLE
Indieningen worden steeds gekoppeld aan groep 1

### ISSUE THREAD

**Issue by gusvanpoucke** [SELab-2/UGent-4#193]
Als een student een file upload als indiening op assignmentPage dan worden alle groepen opgevraagd, de eerste groep word geselecteerd en dan word de indiening aan die groep gekoppeld

**Comment by sPAICEcake** [comment]
Oei, dat is idd ni de bedoeling, kzal hier morgen eens bekijken

**Comment by sPAICEcake** [comment]
Ik vermoed dat dit is omdat wij superuser zijn, en dus altijd alle groepen krijgen, in plaats van enkel de groep waarin de student is ingeschreven. Een mooiere manier om het te implementeren zal dit wss wel oplossen voor iedereen

**Comment by sPAICEcake** [comment]
opgelost in deze commit:  #7dc512d (wou PR maken maar lokale branch was per ongeluk direct naar frontend gepushed)
