### ISSUE TITLE
bug groepen page

### ISSUE THREAD

**Issue by mathis2003** [SELab-2/UGent-4#204]
Er lijkt een bug te zijn in de groupsPage.
In de lijst van studenten voor een groep worden de namen precies niet gerenderd.
 
![Schermafbeelding 2024-04-28 om 15 04 42](https://github.com/SELab-2/UGent-4/assets/49711425/e2a8454f-6f21-40a2-b13c-14ce1d2ea51d)

**Comment by mathis2003** [comment]
Er staan ook nog andere dingen in zoals een console log die op termijn er uit zou moeten.
En nog wat strings die niet geïnternationaliseerd zijn.

**Comment by gusvanpoucke** [comment]
De namen die niet verschijnen lijkt mij te zijn omdat de mensen in die groepen niet ingeschreven zijn voor het vak.

**Comment by gusvanpoucke** [comment]
https://github.com/SELab-2/UGent-4/pull/205 de rest zou hier opgelost moeten zijn

**Comment by Bendemeurichy** [comment]
> De namen die niet verschijnen lijkt mij te zijn omdat de mensen in die groepen niet ingeschreven zijn voor het vak.

klopt, dit is doordat er dingen in de backend zitten dat door normaal gebruik niet zouden gebeuren normaal gezien.
De pagina haalt enkel de namen van studenten van het vak op en de groepen hebben mensen die niet zijn ingeschreven.
