### ISSUE TITLE
Knop die pop-up opent en alle ingeschreven studenten toont op vak pagina

### ISSUE THREAD

**Issue by sPAICEcake** [SELab-2/UGent-4#209]

**Comment by sPAICEcake** [comment]
In deze pull request is de pop up toegevoegd: #213 
Het enige probleem is nog wanneer de studenten nog niet zijn ingeladen, maar dit zou na het toevoegen van de 'loading_fix' geen probleem meer mogen zijn

**Comment by gusvanpoucke** [comment]
Misschien een gelijkaardige manier om de studenten die in een bepaalde groep zitten te kunnen bekijken?
Nu toont het alleen het groepsnummer

**Comment by sPAICEcake** [comment]
Toevoegen op submissionPage

**Comment by sPAICEcake** [comment]
Toegevoegd en deftig in de layout verwerkt
