### ISSUE TITLE
Indieningen verdwijnen als groepen veranderen

### ISSUE THREAD

**Issue by gusvanpoucke** [SELab-2/UGent-4#220]
Wanneer er een aanpassing gebeurt aan de groepen voor een project verdwijnen alle indieningen voor dat project.
Misschien een waarschuwing op de groepen pagina of de optie om groepen te veranderen uitschakelen als er al indieningen gebeurd zijn?
Betekent wel dat als er een nieuwe student word toegevoegd aan een vak dat die dan geen groep kan joinen.

**Comment by ArnoutAllaert** [comment]
Gebeurd* :sweat_smile:

**Comment by gusvanpoucke** [comment]
> Gebeurd* 😅

gefixt haha

**Comment by Bendemeurichy** [comment]
> Wanneer er een aanpassing gebeurt aan de groepen voor een project verdwijnen alle indieningen voor dat project. Misschien een waarschuwing op de groepen pagina of de optie om groepen te veranderen uitschakelen als er al indieningen gebeurd zijn? Betekent wel dat als er een nieuwe student word toegevoegd aan een vak dat die dan geen groep kan joinen.

normaal wordt de id niet aangepast als de groepgrootte niet veranderd, dan is het normaal een patch die wordt opgeroepen

**Comment by ArnoutAllaert** [comment]
verandert* :sob:

**Comment by Bendemeurichy** [comment]
te snel getypt :skull:

**Comment by sPAICEcake** [comment]
Dus we voegen dan een warning pop up wanneer de groepgrootte wordt aangepast, of als de groepen helemaal opnieuw verdeeld worden?

**Comment by gusvanpoucke** [comment]
yep, alles dat zou zorgen dat de oude groepen verwijderd worden

**Comment by Bendemeurichy** [comment]
#258
Dit zou opgelost worden met deze pull request. Enkel het random herverdelen van groepen zou er nog voor zorgen dat de indieningen worden verwijderd maar dit is logisch. Hiervoor zal ik toch nog een waarschuwing maken @gusvanpoucke

**Comment by gusvanpoucke** [comment]
top, dat zou het probleem moeten oplossen
