### ISSUE TITLE
kalender opschonen

### ISSUE THREAD

**Issue by Bendemeurichy** [SELab-2/UGent-4#236]

**Comment by LGDTimtou** [comment]
Als er geen deadline is op een dag staat dit er wel
![image](https://github.com/SELab-2/UGent-4/assets/73907470/60e00383-5f33-4082-87de-2ba5d1b683be)
Misschien mooier om gewoon te zetten 'geen deadlines op: <datum>' niet?

**Comment by Bendemeurichy** [comment]
#281
