### ISSUE TITLE
Studenten kunnen hun groepsgenoten niet zien

### ISSUE THREAD

**Issue by gusvanpoucke** [SELab-2/UGent-4#266]
![image](https://github.com/SELab-2/UGent-4/assets/159711661/ae6da86b-398d-4a66-9722-b6068ea6712b)
Wanneer de optie dat studenten zelf hun groepen kunnen zien uitstaat en er nog geen indieningen gedaan zijn kan een student onmogelijk zijn groepsgenoten zien. Dit lijkt onhandig.
![image](https://github.com/SELab-2/UGent-4/assets/159711661/a07cd20e-a897-4981-8abb-d86e2e27026b)
Deze knop staat momenteel op de indiening pagina, misschien verplaatsen we deze beter naar de project pagina?

**Comment by sPAICEcake** [comment]
ik zou die laten staan op de submissionPage, maar wel ook toevoegen op de assignmentpage idd

**Comment by sPAICEcake** [comment]
ik heb dit toegevoegd dat als groepen uit staan en de max grootte is niet 1, dan is er een knop om alle groepsleden te zien, anders zie je uw eigen naam. Als groepen kiezen wel aanstaat, dan is het hetzelfde gebleven

ik heb enkel nog een probleempje met het laden van de leden

**Comment by sPAICEcake** [comment]
probleem was het terugkrijgen van een lijst van groepen ipv 1 enkele groep

**Comment by sPAICEcake** [comment]
aangepast in #270
