### ISSUE TITLE
Relatieve ids van groepen kloppen niet

### ISSUE THREAD

**Issue by gusvanpoucke** [SELab-2/UGent-4#272]
![image](https://github.com/SELab-2/UGent-4/assets/159711661/ebb829bb-1a32-45f1-86a3-79ce99ee6a01)
deze wiskunde gaat ervan uit dat alle groepen voor een project opeenvolgende ids hebben en dit is niet zo
Het is makkelijker om gewoon een index bij te houden in de .map()

**Comment by Bendemeurichy** [comment]
ah ja, sorry. ik denk dat ik dit eerst of ergens anders zelfs niet eens zo heb gedaan :sweat_smile:

**Comment by gusvanpoucke** [comment]
https://github.com/SELab-2/UGent-4/pull/274
